services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_api
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:mariadb://db:3306/strange_horizon
    healthcheck:
      test: curl --fail "http://localhost:9000/actuator/health"
      timeout: 5s
      retries: 10
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    ports:
      - "3306:3306"
    env_file:
      - .env
    healthcheck:
      test: mysql --protocol TCP --user root -p"$$MYSQL_ROOT_PASSWORD" --execute "SELECT 1;"
      timeout: 5s
      retries: 10
