FROM maven:3.8.2-openjdk-17-slim AS builder

RUN apt-get update && \
    apt-get install -y \
      libncurses5 \
      libc6 && \
      rm -rf /var/lib/apt/lists/*

COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

FROM openjdk:17-jdk-slim-buster
RUN apt-get update && \
    apt-get install -y \
      curl && \
      rm -rf /var/lib/apt/lists/*
COPY --from=builder /home/app/target/strange-horizon-api-1.0-SNAPSHOT.jar /usr/local/lib/api.jar
EXPOSE 9000
ENTRYPOINT ["java","-jar","/usr/local/lib/api.jar"]
