version: "3.8"

services:
  api:
    build:
      context: .
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/strange_horizon
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=strange_horizon
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/create_api_user.sh:/docker-entrypoint-initdb.d/create_api_user.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
